### PR TITLE
[bin] don't print warning when which/rover is not available

### PR DESCRIPTION
**Pull request by mikz**
just don't print any error output when trying to detect rover

### CODE REVIEW

**Comment by mayorova** [comment]
Maybe we could replace `which rover` with `type -p rover` ? So it can potentially be used on OSs that don't have `which`

**Comment by mikz** [comment]
@mayorova `type -p` outputs `rover is ./lua_modules/bin/rover` for me. Which can't be used as an executable. On zsh `type` is `whence -v`. In apicast image neither of those work: `which`, `whence`, `type`.

**Comment by mayorova** [comment]
@mikz OK, interesting

For me `type -p` returns just the filename (without `-p` it does return `X is`). And apicast's bash does have `type`, but yeah, when run at the startup it's not available indeed.

How about `command -v rover`? :)

It should work find, no? For example, it does find the `openresty` executable:

```docker run quay.io/3scale/apicast:master command -v openresty```

**Comment by mikz** [comment]
@mayorova updated to `command -v`.

**Pull request merged**
