### PR TITLE
README for the IP check policy

### PR DESCRIPTION
**Pull request by davidor**
Adds a README with examples for the IP check policy. Also, places the policy in the correct subsection of the changelog and adds a missing link to JIRA.

### CODE REVIEW

**Comment by mikz** [comment]
@3scale/qe would be good to get your feedback about this. Hopefully, it helps you understand how it works.

**Comment by mayorova** [comment]
Nice, thank you @davidor ! 👍

**Comment by supriya-bharadwaj** [comment]
Hi @mikz , I am unable to edit the files. Do you want me to simply add comments and then you want to incorporate my feedback? Do let me know. Thanks :)

**Comment by mikz** [comment]
@supriya-bharadwaj sorry for that, just have the @3scale/documentation team write permissions to the repo, so you should be free to edit the files in this PR. But anyway, PR comments are fine anyway! Any kind of feedback is much appreciated. 👍

**Comment by pestanko** [comment]
@mikz Looks reasonable, but we will know more when we start with automation.

**Pull request merged**
