### PR TITLE
upgrade openresty

### PR DESCRIPTION
**Pull request by mikz**
to 1.11.2.5-1

### CODE REVIEW

**Comment by mayorova** [comment]
I think it would be useful to have a small table in README with versions of APIcast, and corresponding versions (released) of OpenResty.
I know the info can be taken from the Makefile (not obvious at all) or the CHANGELOG, but I think it would be useful. WDYT @mikz ?

**Comment by mikz** [comment]
@mayorova I don't want to have yet another place to update the version number. 


Ideally I'd have just one place that refers to OpenResty version (and that is not the README).
I plan to drop the version from the Makefile (and depend on master). So it will stay only in the CI config.

**Comment by mayorova** [comment]
@mikz Unfortunately it makes it very difficult for someone who wants to know what OpenResty version APIcast is based on to figure this out...

Test config can't be treated as a source of truth (you can build on one version and test on another). So, the user needs to rely on the CHANGELOG. Which is fine, but not very friendly, as you need to browse through the whole history to see what was the last time the version was bumped before the release you are interested in.

I understand the concern - the docs can get outdated when the code changes. But keeping the docs up to date is a part of the maintenance process. In this case it's just about adding one new line on each final release. But OK....

**Comment by mikz** [comment]
@mayorova we only distribute Docker and then you don't have to care about the OpenResty version. If we would publish RPMs they'd have version constraint and you'd not have to care either.

If you want to run APIcast how we run it and build it - follow the CI. That is the source of truth as that one builds and pushes upstream images.

If you want to know what OpenResty version was some released version using just get it from docker:

```shell
docker run quay.io/3scale/apicast:v3.1.0-rc1 openresty -v
```

**Pull request merged**
