### PR TITLE
remove unused backend client

### PR DESCRIPTION
**Pull request by eguzki**

### CODE REVIEW

**Comment by eguzki** [comment]
Broken link issue fixed in https://github.com/3scale/APIcast/pull/1492

**Comment by eguzki** [comment]
@tkan145 is this `____http_call` location being used? maybe for backend?

**Comment by tkan145** [comment]
It's being used [here](https://github.com/3scale/APIcast/blob/master/gateway/src/resty/http_ng/backend/ngx.lua#L26). However, I don't think we are currently using ngx backend, [default](https://github.com/3scale/APIcast/blob/master/gateway/src/resty/http_ng.lua#L247) is resty backend.

**Review by tkan145 — APPROVED** [review]
LGTM

**Pull request merged**
