### PR TITLE
New Resource Owner Template Oauth Flow files - generalised

### PR DESCRIPTION
**Pull request by tnscorcoran**
These are breaking changes - expecting feedback on refined way to do this.

### CODE REVIEW

**Comment by VinayBhalerao** [comment]
This would not support and break authorization code flow, right?

I think we should have a clean way to plug and execute all four flows 1) Authorization code flow (default) 2) client credential 3) resource owner 4) Implicit flow just by separating the ``grant_type`` parameter.

**Comment by andrewdavidmackenzie** [comment]
Vinay, that is the intention....but to come up with code that enables all 4
flows we want to see what it takes to do each one.

This PR would break other flow and will not be merged....but we still want
to see it....

**Comment by VinayBhalerao** [comment]
I understand now

**Comment by mikz** [comment]
Closing. Will be kept on github as a reference.

**Pull request closed without merging**
