### PR TITLE
[WIP] URL rewriting

### PR DESCRIPTION
**Pull request by mayorova**

### CODE REVIEW

**Comment by davidor** [comment]
@mayorova : I added a URL rewriting policy for the new policy chain system. Could you please take a look and see if it suits your use case? Let me know if you think this PR can be closed.

**Comment by mayorova** [comment]
@davidor This PR can definitely be closed, but please don't remove the branch yet.
I'll check out https://github.com/3scale/apicast/pull/529 and add my comments if some features are missing.

**Comment by mikz** [comment]
@mayorova btw GitHub keeps the diff even when the branch is deleted (and it can be restored at any time when someone needs to checkout).

**Comment by mayorova** [comment]
@mikz Yes, I know, but there might be still someone using this branch... I'll try the new one and write up some docs on how to use it.

**Pull request closed without merging**
