### PR TITLE
[example] update add-ssl example

### PR DESCRIPTION
**Pull request by mikz**
Use builtin HTTPS functionality instead of a customization.

/cc @3scale/documentation

### CODE REVIEW

**Comment by mikz** [comment]
@4integration do you have any feedback on this?

**Comment by 4integration** [comment]
I have looked at the configuration and it is the same as I have but I am using docker-compose and .env file.
But noticed that the image is different.
I have used:
`registry.access.redhat.com/3scale-amp22/apicast-gateway:1.8`
and could not get HTTPS to work so tested with the same as you
`quay.io/3scale/apicast:master`

That makes the HTTPS listener going and responding but getting 

```
C:\>curl -v https://gwdomain.com:8443/_threescale/healthz
*   Trying 10.57.49.13...
* Connected to gw.domain.com (10.57.49.13) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Apps\curl-7.46.0-win64\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Unknown (21):
* TLSv1.2 (IN), TLS alert, Server hello (2):
* error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
* Closing connection 0
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

**Comment by mayorova** [comment]
@4integration `registry.access.redhat.com/3scale-amp22/apicast-gateway:1.8` image corresponds to the `v3.2.0` of the APIcast upstream.
These new `APICAST_HTTPS_*` environment variables appeared after the release, and currently are not available in the productized APIcast image (only in the latest upstream – `quay.io/3scale/apicast:master`).
See the entry `ENV variables to make APIcast listen on HTTPS port` in the [CHANGELOG](https://github.com/3scale/apicast/blob/master/CHANGELOG.md).

For `registry.access.redhat.com/3scale-amp22/apicast-gateway:1.8` the old approach still needs to be used.

**Comment by mikz** [comment]
@4integration the example shows the curl call with `--cacert` param to expect the self signed certificate.

**Comment by 4integration** [comment]
@mayorova thanks a lot for the clarification.
Since it didn't work just to pick the latest image
`registry.access.redhat.com/3scale-amp22/apicast-gateway:1.8`

but now I got it working :)

The only things I have changed are:
* Changed volume mount point for certs
* Using absolute path for certs

So 1-2 of these caused the issue, now solved.

**Pull request merged**
